/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthDivision;


import Business.HealthDepartment.PatientDirectory;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sindhu
 */
public class AssistantWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaPanel
     */
    JPanel userProcessContainer;
     PatientDirectory patient;
     String emp_id = null;String emp_name=null;
     enum status{
         TestCompleted
     }

    public AssistantWorkAreaPanel(JPanel userProcessContainer,String emp_id,String emp_name) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.emp_id = emp_id;
       this.emp_name = emp_name;
       this.patient = new PatientDirectory();
        patientTable.getTableHeader().setFont(new Font("TImes New Roman",Font.BOLD,18));
        patientTable.setRowHeight(30);
       patientTable.setRowMargin(10);
        populateTable();
       AssistantLabelName.setText("Hello User:"+emp_name);
    }
    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)patientTable.getModel();
         MongoClient mongoClient = new MongoClient("localhost", 27017); 
        DB db = mongoClient.getDB("TestDB");
        DBCollection userCollection = db.getCollection("PatientDetails");
        DBCursor cursor = null;
        cursor = userCollection.find();
        dtm.setRowCount(0);
        while(cursor.hasNext()){
            Object[] row = new Object[dtm.getColumnCount()];
            DBObject obj = cursor.next();
            if(obj.get("AssistantId").equals(emp_id)){
                row[0] = obj.get("_id");
                row[1] = obj.get("Name");
                row[2] = obj.get("Status");
                dtm.addRow(row);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bpField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tempField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        heartrateField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pulseField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        AssistantLabelName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        patientTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        patientTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Patient name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientTable.setRowHeight(20);
        patientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patientTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(500, 110, 452, 170);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Patient Name:");
        add(jLabel1);
        jLabel1.setBounds(630, 330, 120, 22);

        patientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(113, 88, 20), 3));
        patientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameActionPerformed(evt);
            }
        });
        add(patientName);
        patientName.setBounds(760, 330, 150, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Blood Pressure:");
        add(jLabel2);
        jLabel2.setBounds(620, 390, 130, 22);

        bpField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(113, 88, 20), 3));
        add(bpField);
        bpField.setBounds(760, 390, 150, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Temperature:");
        add(jLabel3);
        jLabel3.setBounds(640, 450, 110, 22);

        tempField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(113, 88, 20), 3));
        add(tempField);
        tempField.setBounds(760, 450, 150, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("HeartBeat rate:");
        add(jLabel4);
        jLabel4.setBounds(630, 510, 140, 22);

        heartrateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(113, 88, 20), 3));
        add(heartrateField);
        heartrateField.setBounds(760, 510, 150, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Pulse:");
        add(jLabel5);
        jLabel5.setBounds(700, 580, 50, 22);

        pulseField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(113, 88, 20), 3));
        add(pulseField);
        pulseField.setBounds(760, 580, 150, 30);

        addBtn.setBackground(new java.awt.Color(204, 102, 0));
        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addBtn.setText("Add ");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn);
        addBtn.setBounds(760, 670, 71, 30);

        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(imgLabel);
        imgLabel.setBounds(1340, 530, 100, 530);

        AssistantLabelName.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        AssistantLabelName.setText("jLabel6");
        add(AssistantLabelName);
        AssistantLabelName.setBounds(60, 50, 240, 30);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setText("Your Patients");
        add(jLabel6);
        jLabel6.setBounds(630, 40, 180, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)patientTable.getModel();
        int selectedRow = patientTable.getSelectedRow();
          MongoClient mongoClient = new MongoClient("localhost", 27017); 
        DB db = mongoClient.getDB("TestDB");
        DBCollection userCollection = db.getCollection("PatientDetails");
        BasicDBObject queryObj = new BasicDBObject();
        if(selectedRow <0 ){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning!",JOptionPane.WARNING_MESSAGE);
        }else{
            String patient_id = (String) patientTable.getValueAt(selectedRow,0);
            int temp = Integer.parseInt(tempField.getText());
            int bp = Integer.parseInt(bpField.getText());
            int heartRate = Integer.parseInt(heartrateField.getText());
            int pulse = Integer.parseInt(pulseField.getText());
            queryObj.put("_id", patient_id);
            BasicDBObject newObj = new BasicDBObject();
            newObj.put("$set", new BasicDBObject().append("Status", status.TestCompleted.toString()).append("Temperature", temp).append("BP", bp).append("HeartRate", heartRate).append("Pulse", pulse));
            userCollection.update(queryObj, newObj);
            populateTable();
            JOptionPane.showMessageDialog(null, "Necessary test taken for this user", "Suceess",JOptionPane.PLAIN_MESSAGE);      
                   
        }
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void patientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = patientTable.getSelectedRow();
        String patient_name = (String) patientTable.getValueAt(selectedRow,1);
        patientName.setText(patient_name);
        patientName.setEditable(false);
    }//GEN-LAST:event_patientTableMouseClicked

    private void patientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AssistantLabelName;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField bpField;
    private javax.swing.JTextField heartrateField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientName;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField pulseField;
    private javax.swing.JTextField tempField;
    // End of variables declaration//GEN-END:variables
}
