/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;


import Encrypt.Password.PasswordUtils;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageWelfareEmployeePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageWelfareEmployeePanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        employeeTable.getTableHeader().setFont(new Font("TImes New Roman",Font.BOLD,18));
        employeeTable.setRowHeight(30);
        employeeTable.setRowMargin(10);
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        MongoClient mongoClient = new MongoClient("localhost", 27017); 
        DB db = mongoClient.getDB("TestDB");
        DBCollection userCollection = db.getCollection("WelfareEmpDetails");
        DBCursor cursor = null;
        cursor = userCollection.find();
        model.setRowCount(0);
        while(cursor.hasNext()){
            Object[] row = new Object[model.getColumnCount()];
            DBObject obj = cursor.next();
            row[0] = obj.get("EmpName");
            row[1] = obj.get("EmpRole");
            row[2] = obj.get("Division");
            model.addRow(row);
        }
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        empRole = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empDivision = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pwdField = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        employeeTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        employeeTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee  Name", "Role", "Division"
            }
        ));
        employeeTable.setGridColor(new java.awt.Color(255, 255, 255));
        employeeTable.setRowHeight(25);
        employeeTable.setSelectionBackground(new java.awt.Color(37, 51, 62));
        jScrollPane1.setViewportView(employeeTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(390, 190, 660, 220);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Role:");
        add(jLabel1);
        jLabel1.setBounds(610, 490, 70, 28);

        empRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option....", "Contribution Manager", "Beneficiary Manager" }));
        empRole.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(empRole);
        empRole.setBounds(710, 490, 160, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2);
        jLabel2.setBounds(600, 430, 70, 28);

        empName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empName.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(empName);
        empName.setBounds(710, 430, 160, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Division:");
        add(jLabel3);
        jLabel3.setBounds(585, 550, 110, 28);

        empDivision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option....", "Contribution Division", "Beneficiary Division" }));
        empDivision.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(empDivision);
        empDivision.setBounds(710, 550, 160, 30);

        submitJButton.setBackground(new java.awt.Color(102, 0, 102));
        submitJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(700, 690, 80, 40);

        backJButton.setBackground(new java.awt.Color(153, 102, 0));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0)));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(110, 720, 110, 50);

        imageLabel.setText("Create  Account");
        add(imageLabel);
        imageLabel.setBounds(1539, -20, 91, 1070);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Create Employee Account");
        add(jLabel4);
        jLabel4.setBounds(480, 70, 450, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Password:");
        add(jLabel5);
        jLabel5.setBounds(570, 600, 110, 28);

        pwdField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(pwdField);
        pwdField.setBounds(710, 600, 160, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
         String salt = PasswordUtils.getSalt(30);
         String emp_name = empName.getText();
         String emp_role = empRole.getSelectedItem().toString();
         String emp_division = empDivision.getSelectedItem().toString();
         String emp_password = pwdField.getText();
          String password = PasswordUtils.generateSecurePassword(emp_password, salt);
          MongoClient mongoClient = new MongoClient("localhost", 27017); 
        DB db = mongoClient.getDB("TestDB");
        DBCollection userCollection = db.getCollection("WelfareEmpDetails");
        BasicDBObject bO = new BasicDBObject();
	bO.put("EmpName", emp_name);
        bO.put("EmpRole", emp_role);
        bO.put("Division", emp_division);
        bO.put("Password", emp_password);
         bO.put("Password", password);
        bO.put("Saltvalue",salt);
        userCollection.insert(bO);
        JOptionPane.showMessageDialog(null, "Created Account for Employee Successfully");
        populateTable();

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkAreaPanel sysAdminwjp = (AdminWorkAreaPanel) component;
        

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox empDivision;
    private javax.swing.JTextField empName;
    private javax.swing.JComboBox empRole;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
