/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;


import Encrypt.Password.PasswordUtils;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageHealthEmployeesPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageHealthEmployeesPanel(JPanel userProcessContainer) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        empTable.getTableHeader().setFont(new Font("TImes New Roman",Font.BOLD,18));
        empTable.setRowHeight(30);
        empTable.setRowMargin(10);
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        model.setRowCount(0);
         MongoClient mongoClient = new MongoClient("localhost", 27017); 
         DB db = mongoClient.getDB("TestDB");
         DBCollection userCollection = db.getCollection("HealthEmpDetails");
         DBCursor cursor = null;
         cursor = userCollection.find();
         model.setRowCount(0);
         while(cursor.hasNext()){
             Object[] row = new Object[model.getColumnCount()];
             DBObject obj = cursor.next();
             row[0] = obj.get("_id");
             row[1] = obj.get("EmpName");
             row[2] = obj.get("EmpRole");
             row[3] = obj.get("Division");
             model.addRow(row);
         }
        
         
    }

   
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        empRole = new javax.swing.JComboBox();
        empDivision = new javax.swing.JComboBox();
        pwdField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        empTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Role", "Division"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empTable.setRowHeight(25);
        jScrollPane1.setViewportView(empTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(490, 230, 730, 190);

        submitJButton.setBackground(new java.awt.Color(102, 0, 102));
        submitJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(810, 720, 90, 40);

        backJButton.setBackground(new java.awt.Color(153, 102, 0));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0)));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(240, 810, 90, 40);
        add(imageLabel);
        imageLabel.setBounds(1740, -20, 20, 1080);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2);
        jLabel2.setBounds(680, 470, 70, 28);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Role:");
        add(jLabel1);
        jLabel1.setBounds(690, 530, 70, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Division:");
        add(jLabel3);
        jLabel3.setBounds(670, 590, 110, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Password:");
        add(jLabel5);
        jLabel5.setBounds(650, 640, 110, 28);

        empName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empName.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(empName);
        empName.setBounds(790, 470, 160, 30);

        empRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option....", "Manager", "Doctor", "Assistant" }));
        empRole.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(empRole);
        empRole.setBounds(790, 530, 160, 30);

        empDivision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option....", "Management Division", "Services Division" }));
        empDivision.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(empDivision);
        empDivision.setBounds(790, 590, 160, 30);

        pwdField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 102)));
        add(pwdField);
        pwdField.setBounds(790, 640, 160, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Create Employee Account");
        add(jLabel4);
        jLabel4.setBounds(650, 140, 450, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
         String salt = PasswordUtils.getSalt(30); 
        String emp_name = empName.getText();
         String emp_role = empRole.getSelectedItem().toString();
         String emp_division = empDivision.getSelectedItem().toString();
         String emp_password = pwdField.getText();
         String password = PasswordUtils.generateSecurePassword(emp_password, salt);
          MongoClient mongoClient = new MongoClient("localhost", 27017); 
        DB db = mongoClient.getDB("TestDB");
        DBCollection userCollection = db.getCollection("HealthEmpDetails");
        BasicDBObject bO = new BasicDBObject();
        int count = (int)userCollection.count();
        String emp_id = "E00"+count;
        bO.put("_id",emp_id);
	bO.put("EmpName", emp_name);
        bO.put("EmpRole", emp_role);
        bO.put("Division", emp_division);
        bO.put("Password", password);
        bO.put("Saltvalue",salt);
        userCollection.insert(bO);
        JOptionPane.showMessageDialog(null, "Created Account for Employee Successfully");
        populateTable();
        
    }//GEN-LAST:event_submitJButtonActionPerformed
    
    
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkAreaPanel sysAdminwjp = (AdminWorkAreaPanel) component;
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox empDivision;
    private javax.swing.JTextField empName;
    private javax.swing.JComboBox empRole;
    private javax.swing.JTable empTable;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
